Repository 2025-LIKELION-BuyDobong/2025-LIKELION-BuyDobong-BE, pull requests merged in 2025-08, with the labels that each got.

#6 Feat/5 store merchant
  build.gradle
  src/main/java/com/dobongsoon/BuyDobong/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dobongsoon/BuyDobong/common/response/ErrorCode.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/controller/StoreController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/dto/StoreCreateRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/dto/StoreOpenRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/dto/StoreResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/model/Store.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/repository/StoreRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/service/StoreService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/service/StoreServiceImpl.java
Labels: ✨ Feat

#8 Feat/7 product merchant
  src/main/java/com/dobongsoon/BuyDobong/common/response/ErrorCode.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/controller/ProductController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/dto/ProductCreateRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/dto/ProductDealRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/dto/ProductResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/model/Product.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/model/StockLevel.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/repository/ProductRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/service/ProductService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/service/ProductServiceImpl.java
Labels: ✨ Feat

#16 ✨ Feat: 상점/상품 검색 및 조회 구현
  src/main/java/com/dobongsoon/BuyDobong/common/config/SecurityConfig.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/repository/ProductRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/search/controller/SearchController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/search/dto/SearchResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/search/service/SearchService.java
Labels: ✨ Feat

#18 ✨ Feat: 소비자 추가
  src/main/java/com/dobongsoon/BuyDobong/common/config/SecurityConfig.java
  src/main/java/com/dobongsoon/BuyDobong/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/Consumer.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/ConsumerPreference.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerPreferenceRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerRepository.java
Labels: ✨ Feat

#20 ✨ Feat: 관심 상점 기능 추가
  src/main/java/com/dobongsoon/BuyDobong/common/config/SecurityConfig.java
  src/main/java/com/dobongsoon/BuyDobong/common/response/ErrorCode.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/controller/FavoriteStoreController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/FavoriteStoreRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/FavoriteStoreResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/ConsumerPreference.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/FavoriteStore.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/FavoriteStoreRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/service/FavoriteStoreService.java
Labels: ✨ Feat

#21 ✨ Feat: 관심 상점 기능 추가
  src/main/java/com/dobongsoon/BuyDobong/common/config/SecurityConfig.java
  src/main/java/com/dobongsoon/BuyDobong/common/response/ErrorCode.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/controller/FavoriteStoreController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/FavoriteStoreRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/FavoriteStoreResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/ConsumerPreference.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/FavoriteStore.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/FavoriteStoreRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/service/FavoriteStoreService.java
Labels: ✨ Feat

#24 ✨ Feat: 관심 키워드 기능 추가
  src/main/java/com/dobongsoon/BuyDobong/common/config/SecurityConfig.java
  src/main/java/com/dobongsoon/BuyDobong/common/response/ErrorCode.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/controller/ConsumerKeywordController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/KeywordRegisterResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/KeywordRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/KeywordResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/ConsumerKeyword.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/model/Keyword.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerKeywordRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/KeywordRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/search/controller/SearchController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/search/dto/SearchResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/search/service/SearchService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/service/ConsumerKeywordService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/search/controller/SearchController.java
Labels: ✨ Feat

#30 Deploy/29 cicd docker ec2
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🚀 Deploy

#38 ✨ Feat: 로그인/회원가입 응답에 역할 추가
  src/main/java/com/dobongsoon/BuyDobong/domain/auth/dto/AuthResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/auth/service/AuthServiceImpl.java
Labels: ✨ Feat

#46 ✨ Feat: 상점 등록 통합
  src/main/java/com/dobongsoon/BuyDobong/domain/store/controller/StoreController.java
Labels: ✨ Feat

#50 ✨ Feat: 상점 수정 통합
  src/main/java/com/dobongsoon/BuyDobong/domain/store/controller/StoreController.java
Labels: ✨ Feat

#52 🔨 Refactor: 상점 상세 조회 API 처리 방법 변경
  src/main/java/com/dobongsoon/BuyDobong/common/s3/DummyS3Service.java
Labels: ♻️ Refactor

#61 ✨ Feat: 관심 상점 특가 알림 생성 구현
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/dto/PushPreferenceRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/controller/NotificationController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/dto/NotificationResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/model/Notification.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/repository/NotificationRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/service/NotificationService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerPreferenceRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/FavoriteStoreRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/service/ProductServiceImpl.java
Labels: ✨ Feat

#62 ✨ Feat: PWA 구독 정보 관련 기능 구현
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/controller/PushController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/dto/PushSubscriptionRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/dto/PushSubscriptionResponse.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/model/PushSubscription.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/repository/PushSubscriptionRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/service/PushSubscriptionService.java
Labels: ✨ Feat

#63 ✨ Feat: 관심 키워드 특가 알림 생성 구현
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/model/Notification.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/service/NotificationService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerKeywordHit.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerKeywordRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/product/service/ProductServiceImpl.java
Labels: ✨ Feat

#65 🐛 Bugfix: PWA 구독 정보 등록 API 수정
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/controller/ConsumerKeywordController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/controller/FavoriteStoreController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/notification/controller/NotificationController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/controller/PushController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/dto/PushSubscriptionRequest.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/push/model/PushSubscription.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/recent/controller/RecentStoreController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/repository/ConsumerRepository.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/search/controller/SearchController.java
  src/main/java/com/dobongsoon/BuyDobong/domain/consumer/service/ConsumerService.java
  src/main/java/com/dobongsoon/BuyDobong/domain/store/controller/StoreController.java
Labels: 🐛 BugFix
